import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextUI } from "@/providers/nextui-provider";
import { ThemeProvider } from "@/providers/next-theme-provider";

const degular = localFont({
  src: "./fonts/Degular-Regular.otf",
  variable: "--font-degular",
  weight: "100 900",
})
const degularLight = localFont({
  src: "./fonts/Degular-Light.otf",
  variable: "--font-degular-light",
  weight: "100 900",
})
const degularVariable = localFont({
  src: "./fonts/DegularVariable.ttf",
  variable: "--font-degular-variable",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${degular.variable} ${degularLight.variable} ${degularVariable.variable}  font-[family-name:var(--font-degular)]  antialiased`}
      >
        <NextUI>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            themes={["light", "dark"]}
          >
         
              {children}
          
          </ThemeProvider>
        </NextUI>
      </body>
    </html>
  );
}

